# File Version - DO NOT CHANGE
config-version: 1

# Core plugin settings
core:
  # Should the startup banner be shown?
  show_banner: true
  # Which players should count as owners
  # The recommended way for adding owners is by setting the 'szlaban.owner' permission node
  # WARNING: All listed players will have ownership permissions on the plugin!
  owners: []


# Map of modules to enable and booleans for whether they should be enabled
modules:
  advisories: true
  firewall: true
  fail2ban: false

# Settings for the advisory module
advisories:
  # Whether to show owners the first-time login message
  show-first-login-message: true

  # List of advisory IDs that have been ignored
  ignored-advisories:
  # - online_mode
  # - whitelist
  # - rcon
  # - chat_signing

  # Whether to allow writing directly to other configuration files (i.e.
  # those not managed by this plugin).
  # Useful if you want to toggle settings not normally editable in-game
  # (like `enforce-secure-profile`), but there's a small chance it'll
  # cause instabilities.
  allow-other-config-changes: true

# Settings for the firewall module
firewall:
  # What engine to use for firewall management
  # Unless you have a specific configuration in mind, just use 'internal'
  # Allowed values: internal, protocollib, event
  #   internal:     Uses PaperMC's internals for filtering ALL packets - most powerful, completely rejects everything
  #   protocollib:  Use ProtocolLib for filtering connections - good fallback, will block MOST connections
  #   event:        Use Bukkit's Event API for filtering connections - rejects certain classes of login/status ping events
  engine: internal

  # How to deal with blocked traffic
  # Allowed values: drop, log
  #   drop:  Terminates blocked connections (also logs them)
  #   log:   Logs blocked connections (not very useful)
  response: drop

  # A list of files containing IPs/CIDR ranges that should be blocked
  # - These should be text files with one IP/CIDR entry per line
  # - Comments should start with #
  # - Files can be either local or remote
  # - Remote files should only be unauthenticated HTTP/S
  # - Local file paths are relative to the plugin's config directory
  #     i.e. plugins/Szlaban/
  blocklists:
    - blocklist.cfg
    - https://github.com/pebblehost/hunter/raw/refs/heads/master/ips.txt

  # A list of files containing IPs/CIDR ranges that should always be allowed
  # to connect. This takes precedence over blocklists.
  # By default, the plugin operates in allow-all mode, making this option irrelevant
  # unless you wish to whitelist IPs within a blocked range.
  # While there isn't a deny-all mode by default, this can be achieved quite easily
  # by adding 0.0.0.0/0 and ::/0 to your blocklists.
  allowlists:
    - allowlist.cfg

  # How often (in seconds) the plugin should automatically re-read the contents of
  # each kind of blocklist file.
  # This does not affect the config reload command.
  # Special values:
  #    0:  Update only when file contents are changed (only works with local)
  #   -1:  Never update after initial load
  blocklist-update-rate:
    local: 0
    remote: 7200

  # ==== ADVANCED FIREWALL SETTINGS ====
  # If you want more from your firewall, you can play around with these settings.

  # Whether to enable IP information lookup for more advanced filters.
  # This will run after basic IP filtering to avoid unnecessary requests for IPs
  # that are blocked anyway.
  # This may incur performance penalties if your server is getting too many connections
  # at once, but that's what caching is for!
  enable-ip-lookup: false

  # Advanced filtering rules
  # The firewall will match these directly against the API output from the GeoIP database.
  # The format consists of a key-value mapping, where all values in the provided lists will
  # be checked against the key, which is a representation of the path in the JSON output
  # demonstrated below.
  advanced-block-filters:
    - key: asn
      values: &asn
        - 1136
    - key: "connection.asn"
      values: *asn
    - key: country_code
      values:
        - NL

  # The API backend to use for IP info.
  # You may want to change this if you are hitting rate limits (429)
  # Just uncomment the other line, and comment the previous one.

  # More data, rate-limit 1 req/s. Docs: https://ipwhois.io/docs
  _api-backend: 'https://ipwho.is/%s'
  # Limited data, no specified rate-limit. Docs: https://seeip.org/
  # _api-backend: 'https://api.seeip.org/geoip/%s'




# Settings for the fail2ban module
fail2ban:

  # TODO: add config options

# The following are internal settings not intended for use by normal users of the plugin.
# You will NOT RECEIVE SUPPORT if you enable these without knowing what they do. Don't ask
# for documentation. If you really want to know what these do, read the source code.
_internal:
  super-secret-setting: false